name: signalr_core
description: ASP.NET Core SignalR Client written for Dart that is platform-independent, and can be used on both the command-line and the browser.
version: 1.1.1
homepage: https://github.com/jamiewest/signalr_core

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^1.1.0
  tuple: ^2.0.2
  web_socket_channel: ^2.4.0
  sse_client:
    git: https://github.com/codersstudio/sse_client.git
  equatable: ^2.0.5

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
